name: UUIDCheck
main: cn.lanink.uuidcheck.UUIDCheck
version: "1.0.2-SNAPSHOT"
api:
  - 1.0.0
load: POSTWORLD
author: lt_name
depend:
  - "EasySQL"
  - "DbLib"

commands:
  ucheck:
    description: ucheck
    usage: /uuidcheck
    permission: uuidcheck.op
permissions:
  uuidcheck.op:
    description: ""
    default: op