name: UUIDCheck
main: name.UUIDCheck.UUIDCheck
version: "1.0.0"
api:
  - 1.0.0
load: POSTWORLD
author: lt_name
loadbefore:
  - AutoUpData

commands:
  ucheck:
    description: ucheck
    usage: /uuidcheck
    permission: uuidcheck.op
permissions:
  uuidcheck.op:
    description: ""
    default: op